# Generated by Django 5.0.7 on 2024-07-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("start_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_necessity", models.BooleanField(default=False)),
            ],
        ),
    ]
