# Generated by Django 5.0.7 on 2024-10-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_monthly_income"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthly_income",
            name="income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
